# 個人課題のサンプルプログラム
- filepathで指定した画像ファイルを読み込み、その画像のRGB値の平均をNumpyのArrayで【行ベクトルで】返す関数　ext_mean_rgb(filepath)
- RGB値をnumpy array、qcolor=np.array([r,g,b])で与えられると[赤,橙,黄,緑,青,紫,ピンク,白,グレー,黒]の重みを成分とする10次元ベクトルが出力される関数gen_color_vec(qcolor)

## やること
- 「15分で理解する色彩と心理学の関係－色が人間の心に与える影響」(https://re-sta.jp/color-psychology-7787 )を読みながら印象を表す語と10色の関係を表す行列を作ってみよう
- 画像データをファイルパスで指定するとその画像データの色の印象から喚起される語が出力されるようなプログラムを作ってみよう


### ヒント
- 印象を表す語と10色(赤,橙,黄,緑,青,紫,ピンク,白,グレー,黒)の関係を表す行列を$A$作成するためには、その語が書いてあれば「1」、書いてなければ「0」で表現する行列を作成すればよい。
- 上記のext_mean_rgb(filepath)、gen_color_vec(qcolor)を使えば、画像データから10色の要素からなる10次元のベクトルが出力される。
- あとは、${\bf y}=A{\bf x}$を計算すれば、${\bf y}$が各語の重みになるため、重みの大きいものから順番に列挙できれば完成


In [24]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
from PIL import Image
import numpy as np
import os

# filepathで指定した画像ファイルを読み込み、その画像のRGB値の平均をNumpyのArrayで【行ベクトルで】返す関数　ext_mean_rgb(filepath)
def ext_mean_rgb(filepath):
  image = np.array(Image.open(filepath).convert('RGB')).reshape(-1,3)
  return np.array([np.mean(image[:,0]),np.mean(image[:,1]),np.mean(image[:,2])])

In [0]:
import numpy as np
from scipy.spatial import distance

# RGB値をnumpy array、qcolor=np.array([r,g,b])で与えられると[赤,橙,黄,緑,青,紫,ピンク,白,グレー,黒]の重みを成分とする10次元ベクトルが出力される関数gen_color_vec(qcolor)
def gen_color_vec(qcolor):
  colorvec=np.array([])
  palette=np.array(
      [
       [255,0,0], #赤
      [255,102,0],  #橙
      [255,255,0],  #黄
      [0,128,0],  #緑
      [0,0,255],  #青
      [128,0,128],  #紫
      [255,0,255],  #ピンク
      [255,255,255],  #白
      [128,128,128],  #グレー
      [0,0,0] #黒
      ])
  for col in palette:
    colorvec=np.append(colorvec,distance.euclidean(col,qcolor))
  colorvec=1-colorvec/np.linalg.norm(colorvec,np.inf)
  return colorvec

In [27]:
filepath='/content/kagaya.jpeg'
x=gen_color_vec(ext_mean_rgb(filepath)).reshape(-1,1)
x

array([[0.1559164 ],
       [0.21476393],
       [0.        ],
       [0.34797851],
       [0.37008224],
       [0.66014634],
       [0.21974851],
       [0.05326072],
       [0.79962185],
       [0.29255309]])

In [28]:
x.shape

(10, 1)

In [39]:
# 行列A（色と印象の関係を表す行列）の作成
# 行を印象語20個（上から熱い、強い、暖かい、希望、輝き、刺激的、安らぎ、生鮮、広大、爽やか、神秘的、高貴、やわらかい、明るい、神聖、清潔、シック、不安、かっこいい、静寂）
# 列を10色(左から赤、橙、黄、緑、青、紫、ピンク、白、グレー、黒)
# 印象語に当てはまる場合1,当てはまらない場合0とする
A = np.array(
    [
     [1,0,0,0,0,0,0,0,0,0],
    [1,0,0,0,0,0,0,0,0,1],
    [1,1,0,0,0,0,0,0,0,0],
    [1,1,1,0,1,0,0,0,0,0],
    [0,0,1,0,0,0,0,1,0,0],
    [1,0,1,0,0,0,0,0,0,0],
    [0,0,0,1,1,0,1,0,0,0],
    [0,0,0,1,0,0,0,0,0,0],
    [0,0,0,0,1,0,0,0,0,0],
    [0,0,0,1,1,0,0,1,0,0],
    [0,0,0,0,0,1,0,1,0,0],
    [0,0,0,0,0,1,0,0,0,1],
    [0,1,0,1,0,0,1,0,0,0],
    [1,1,1,0,0,0,0,1,0,0],
    [0,0,0,0,0,1,0,1,0,0],
    [0,0,0,0,0,0,0,1,0,0],
    [0,0,0,0,0,1,0,0,1,1],
    [0,0,0,0,0,1,0,0,1,1],
    [0,0,0,0,0,0,0,0,0,1],
    [0,0,0,0,0,1,0,0,1,1],
    ]
)
A

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 1],
       [0, 1, 0, 1, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 1, 0, 0, 1, 1]])

In [11]:
#重みy
y = np.dot(A,x)
y

array([[0.1559164 ],
       [0.44846949],
       [0.37068033],
       [0.74076256],
       [0.05326072],
       [0.1559164 ],
       [0.93780926],
       [0.34797851],
       [0.37008224],
       [0.77132147],
       [0.71340707],
       [0.95269943],
       [0.78249095],
       [0.42394105],
       [0.71340707],
       [0.05326072],
       [1.75232128],
       [1.75232128],
       [0.29255309],
       [1.75232128]])

In [234]:
#印象語の行列
color_word = np.array(
              [
               ["熱い"],
              ["強い"],
              ["暖かい"],
              ["希望"],
              ["輝き"],
              ["刺激的"],
              ["安らぎ"],
              ["生鮮"],
              ["広大"],
              ["爽やか"],
              ["神秘的"],
              ["高貴"],
              ["やわらかい"],
              ["明るい"],
              ["神聖"],
              ["清潔"],
              ["シック"],
              ["不安"],
              ["かっこいい"],
              ["静寂"],
              ])
color_word.shape

(20, 1)

In [235]:
# 印象語の行列と重みを結合
color_image = np.concatenate((y, color_word), axis=1)
color_image

array([['0.1559163992032062', '熱い'],
       ['0.4484694885512883', '強い'],
       ['0.370680325014212', '暖かい'],
       ['0.74076256062554', '希望'],
       ['0.053260723059680215', '輝き'],
       ['0.1559163992032062', '刺激的'],
       ['0.9378092554137897', '安らぎ'],
       ['0.3479785072317141', '生鮮'],
       ['0.370082235611328', '広大'],
       ['0.7713214659027223', '爽やか'],
       ['0.7134070659546431', '神秘的'],
       ['0.952699432243045', '高貴'],
       ['0.7824909456134674', 'やわらかい'],
       ['0.4239410480738922', '明るい'],
       ['0.7134070659546431', '神聖'],
       ['0.053260723059680215', '清潔'],
       ['1.7523212800195318', 'シック'],
       ['1.7523212800195318', '不安'],
       ['0.2925530893480821', 'かっこいい'],
       ['1.7523212800195318', '静寂']], dtype='<U32')

In [244]:
# 重みの順に出力
color_image_new = sorted(color_image,key=lambda x:x[0])[::-1]
color_image_new

[array(['1.7523212800195318', '静寂'], dtype='<U32'),
 array(['1.7523212800195318', '不安'], dtype='<U32'),
 array(['1.7523212800195318', 'シック'], dtype='<U32'),
 array(['0.952699432243045', '高貴'], dtype='<U32'),
 array(['0.9378092554137897', '安らぎ'], dtype='<U32'),
 array(['0.7824909456134674', 'やわらかい'], dtype='<U32'),
 array(['0.7713214659027223', '爽やか'], dtype='<U32'),
 array(['0.74076256062554', '希望'], dtype='<U32'),
 array(['0.7134070659546431', '神聖'], dtype='<U32'),
 array(['0.7134070659546431', '神秘的'], dtype='<U32'),
 array(['0.4484694885512883', '強い'], dtype='<U32'),
 array(['0.4239410480738922', '明るい'], dtype='<U32'),
 array(['0.370680325014212', '暖かい'], dtype='<U32'),
 array(['0.370082235611328', '広大'], dtype='<U32'),
 array(['0.3479785072317141', '生鮮'], dtype='<U32'),
 array(['0.2925530893480821', 'かっこいい'], dtype='<U32'),
 array(['0.1559163992032062', '刺激的'], dtype='<U32'),
 array(['0.1559163992032062', '熱い'], dtype='<U32'),
 array(['0.053260723059680215', '清潔'], dtype='<U32'),
 a